// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SaxsSpot.NanoSystemGeneration.Storage.DbContexts;

#nullable disable

namespace SaxsSpot.NanoSystemGeneration.Storage.Migrations
{
    [DbContext(typeof(NanoSystemDbContext))]
    partial class NanoSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SaxsSpot.NanoSystemGeneration.Entities.NanoSystem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float>("CurrentGlobalSize")
                        .HasColumnType("real");

                    b.Property<float>("CurrentNumericalConcentration")
                        .HasColumnType("real");

                    b.Property<int>("CurrentParticleCount")
                        .HasColumnType("integer");

                    b.Property<float>("Excess")
                        .HasColumnType("real");

                    b.Property<DateTime>("GenerationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("GlobalSize")
                        .HasColumnType("real");

                    b.Property<DateTime>("InputDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("K")
                        .HasColumnType("real");

                    b.Property<float>("MaxParticleSize")
                        .HasColumnType("real");

                    b.Property<float>("MinParticleSize")
                        .HasColumnType("real");

                    b.Property<float>("NumericalConcentration")
                        .HasColumnType("real");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("ParticleCount")
                        .HasColumnType("integer");

                    b.Property<int>("ParticleKind")
                        .HasColumnType("integer");

                    b.Property<long>("SeriesId")
                        .HasColumnType("bigint");

                    b.Property<float>("Theta")
                        .HasColumnType("real");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("nano_system");
                });
#pragma warning restore 612, 618
        }
    }
}
